"""
utilities.modn - integers modulo n (ℤₙ)
Eric Conrad
Copyright ©2026 by Eric Conrad.  Licensed under GPL.v3.

DESCRIPTION

    For a given integer n > 1, define the commutative ring ℤₙ.

    If n is (respectively) 1, prime, or composite, then ℤₙ would be
    (respectively) a trivial ring, or a field with a cyclic
    multiplicative group of units, or the ring would contain contain
    nonzero divisors of zero.  (The function "make_Zn" requires that n
    be an integer larger than 1.)

    When n is composite, the group of units is sometimes, but not
    always, cyclic.  Carl Friedrich Gauss (1777-1855) proved that the
    group of units is cyclic if and only if n is 1, 2, 4, a power of
    an odd prime, or twice the power of an odd prime.  For all other
    n, the group of units is a cross product of two or more cyclic
    groups.

    For example, the group of units for the ring ℤ₈ is isomorphic to
    the group ℤ₂×ℤ₂.  The order 2 elements of the group of units of
    the integers between 1 and 8 which are relatively prime to 8, i.e.
    3, 5 and 7. (For example 5 times 5 is 25, which is congruent to 1
    modulo 8, so 5 has order 2.)  The product of any two of these
    values gives the third, for example 3 time 5 15 congruent to 7
    modulo 8, so the group is generated by any two of these numbers.

        Group of units for ℤ₈: (3)×(5) = {1,3,5,7}

        Table 1. Group of units for 2 ≤ n ≤ 20
        ======================================
     n   prime?  zero divisors      group of units
     2    Yes    0                  (1) ≅ ℤ₁
     3    Yes    0                  (2) ≅ ℤ₂
     4    No     0,2                (3) ≅ ℤ₂
     5    Yes    0                  (2) ≅ ℤ₄
     6    No     0,2,3,4            (5) ≅ ℤ₂
     7    Yes    0                  (3) ≅ ℤ₆
     8    No     0,2,4,8            (3)×(5) ≅ ℤ₂×ℤ₂
     9    No     0,3,6              (2) ≅ ℤ₆
    10    No     0,2,4,5,6,8        (3) ≅ ℤ₄
    11    Yes    0                  (2) ≅ ℤ₁₀
    12    No     0,2,3,4,6,8,9,10   (5)×(7) ≅ ℤ₂×ℤ₂
    13    Yes    0                  (2) ≅ ℤ₁₂
    14    No     0,2,4,6,7,8,10,12  (3) ≅ ℤ₆
    15    No     0,3,5,6,9,10,12    (2)×(11) ≅ ℤ₄×ℤ₂
    16    No     0,2,4,6,8,10,12,14 (3)×(7) ≅ ℤ₄×ℤ₂
    17    Yes    0                  (3) ≅ ℤ₁₆
    18    No     0,2,3,4,6,8,9,10,  (11) ≅ ℤ₆
                   12,14,15,16
    19    Yes    0                  (2) ≅ ℤ₁₈
    20    No     0,2,4,5,6,8,10,12, (3)×(11) ≅ ℤ₄×ℤ₂
                   14,15,16,18

       Notes for Table 1:
         (1) The unit group generators are the smallest choices.

LICENSE
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
import textwrap
from math import gcd

from utilities.moremath import Primes
from utilities.primality import is_positive_prime

def _powers(k:int, n:int) -> list:
    """find the powers of k modulo n

    Preconditions

        k is a unit modulo n (i.e. k and n are relatively prime)

    Notes

        In a finite commutive group G written additively, the multiples
        of a given element g form a cyclic subgoup:
            H = {g, 2g, 3g, ..., mg=0}
        The order of g in G is m and m divides the order |G| of G.

        If we consider the group U(R) of units in a commutative ring R,
        then powers of the units take the place of multiples, and the
        multiplicative identity 1 takes the place of the additive
        identity.
    """
    k %= n
    if gcd(k, n) != 1:
        error = f"_power({k},{n}): gcd({k},{n})={gcd(k,n)}"
        error += ", k and n must be relatively prime"
        raise ZeroDivisionError(error)
    powers = [k]
    while powers[-1] != 1:
        powers.append((powers[-1] * k) % n)
    return powers

def _tabulate(orders:dict, inverses:dict, powers:list):
    """use the table of powers to calculate order and inverses

    Example

        Consider the powers of 3 modulo 7:
            H = [3, 2, 6, 4, 5, 1]

        What can we infer about multiplicative inverses and orders?

        Inverses:
            (3, 5) (2, 4) (6, 6) (1, 1)

        Orders:
            |H| = 6

            The order of an element divides the order of the group,
            so possible orders for a group with 6 elements are 1,
            2, 3, and 6.

            Note that if n != 2, then ord(-1) = 2.  So the number
            of units in a cyclic ring is always even unless n=2.
            When n=2, the only unit is 1 and -1 = 1.  For n=6,
            we know that ord(1) = 1 and ord(6) = ord(-1) = 2.

        Deductions from the power sequence:

            ord(3) = 6

            2 is in the second position (index=1, position=2); the
            position 2 divides |H|=6, so ord(2) = 6/2 = 3.

            3 is in the third position; the position 3 divides |H|=6
            so ord(6) = 6/3 = 2.  Of course 6 is another name for -1
            modulo 7 and -1 in any nonbinary group has order 2.

            1 is in position 6 so ord(1) = 6/6 = 1.  But ord(1) = 1
            is true for any multiplicative group.

            That leaves the orders of 4 and 5.

            In ℤ/7ℤ:

                4 = -3 so (-3)^n is either 4^n (if n is even) or
                -4^n (if n is odd). Suppose ord(3)=m.  There are
                four possibilities:
                    -1 is an even power of 3.  Then 3^(m/2)=-1 and
                        4^(m/2)=-1.  Then ord(4) = m.
                    -1 is an odd power of 3.  Then 4^(m/2)=1 and
                        ord(4)=m/2
                    -1 is not a power of 3 and 1 is an even power
                        of 3.  Then ord(4)=m.
                    -1 is not a power of 3 and 1 is an odd power
                        of 3.  Then ord(4)=2m.
                Since 6=-1 is a power of 3, we can eliminate the
                last two possibilities.  We have 3^3=6 so 3 is an
                odd power.  Then we deduce that ord(4)=3.
                    Check: powers of 4 are [4, 2, 1]

                5 = -2, ord(2)=3 and powers of 2 are [2, 4, 1].
                We can tell that -1 is not a power of 2 since ord(3)
                is odd. So we have possibility #4, and ord(5)=6.
                    Check: powers of 5 are [5, 4, 6, 3, 2, 1]

    We don't try to fill out all the orders, at once, but we try to
    get some of the basic ones.
    """
    n = len(powers)
    for i in range(n // 2):
        position = i+1
        m = powers[i]
        if not inverses.get(m):
            p = powers[- position - 1]
            inverses[m] = p
            inverses[p] = m
        if orders.get(m):
            continue
        q,r = divmod(n, position)
        if r == 0:
            orders[m] = q

def _factors(n:int):
    """factor the integer

    NOTE

        This helper function assumes that the small primes list is
        sufficiently long.
    """
    factors = list()
    while True:
        primes = Primes.small_primes()
        for p in primes:
            while n % p == 0:
                factors.append(str(p))
                n //= p
            if n == 1:
                break
        if n == 1:
            break
        if is_positive_prime(n):
            factors.append(str(n))
            break
        Primes.sieve_to(n)
    return factors

def make_Zn(n:int) -> "ℤₙ":
    """create the class ℤₙ"""
    if type(n) != int:
        raise TypeError("n must be an integer.")
    if n < 2:
        raise ValueError(f"{n=} < 2: n must be at least 2.")
    prime = is_positive_prime(n)
        # determine all divisors of zero
    zd = [0]
    if not prime:
        for k in range(1, n):
            if gcd(n, k) > 1:
                zd.append(k)

        # is the group of units cyclic?
    factor_set = set(_factors(n))
    if len(factor_set) == 1:
        cyclic = n % 8 != 0        # prime powers except 2^k, k>2
    elif len(factor_set) == 2:
        cyclic = (2 in factor_set) and (n % 4 != 0)     # 2p^k
    else:
        cyclic = False             # too many prime divisors

    class Zn(int):
        """Zn"""

        __n = n
        __prime = prime
        __zero_divisors = frozenset(zd)
        __units = n - len(zd)
        __cyclic = cyclic
        if n == 2:
            __orders = {1:1}
            __inverses = {1:1}
        else:
            __orders = {1:1, n-1:2}
            __inverses = {1:1, n-1:n-1}

        @classmethod
        def range(cls):
            """elements of the group as an iterable or generator"""
            for i in range(n):
                yield(cls(i))

        @classmethod
        def __order_of(cls, k:int):
            """determine the order of the element"""
            k = k % cls.__n
            if k in cls.__zero_divisors:
                raise ZeroDivisionError(f"order_of: {k} is a zero divisor")
            if k in cls.__orders:
                return cls.__orders[k]
            powers = _powers(k, cls.__n)
            _tabulate(cls.__orders, cls.__inverses, powers)
            return len(powers)

        @property
        def ord(self):
            """return the multiplicative order of an instance

            EXCEPTIONS

                ZeroDivisionError is raised if the instance is a
                zero divisor.
            """
            return self.__order_of(int(self))

        @classmethod
        def additive_order(cls) -> int:
            """return the order of the additive group"""
            return cls.__n

        @classmethod
        def elements(cls) -> list:
            """return the elements as a list"""
            return list(cls(i) for i in range(n))

        @classmethod
        def multiplicative_order(cls) -> int:
            """return the order of the group of units"""
            return cls.__units

        @property
        def cycle(self) -> list:
            """return the multiplicative cycle for the instance

            The return value is the sequence of powers of the
            given instance.  If the instance is a unit, then
            this sequence ends with 1.  If the sequence is a
            zero-divisore, the sequence either ends with 0 or
            ends when a zero divisor other than 0 occurs twice,
            """
            s = [self]
            if self.is_zero_divisor:
                    # messier
                t = {0}
                while s[-1] not in t:
                    t.add(s[-1])
                    s.append(s[-1]*self)
            else:
                    # easier
                while s[-1] != 1:
                    s.append(s[-1]*self)
            return s

        @classmethod
        def is_cyclic(cls) -> bool:
            """returns True if the group of units is cyclic"""
            return cls.__cyclic

        @classmethod
        def modulus(cls) -> int:
            """returns the modulus"""
            return cls.__n

        @classmethod
        def is_field(cls) -> bool:
            return cls.__prime

        @classmethod
        def zero_divisors(cls) -> frozenset:
            return cls.__zero_divisors

        @property
        def is_zero_divisor(self):
            """returns True if the instance is a divisor of zero"""
            return int(self) in self.__zero_divisors

        @property
        def is_primitive(cls) -> object:
            """returns True if the instance is a primitive element"""
            if is_zero_divisor:
                return False
            return self.ord == self.multiplicative_order()

        def __new__(cls, value):
            """constructor"""
            return super(cls, cls).__new__(cls, value % cls.modulus())

        def __neg__(self):
            """arithmetic negation"""
            return Zn(-int(self))

        def __add__(self, other):
            """addition"""
            if isinstance(other, Zn):
                return Zn(int(self) + int(other))
            if type(other) == int:
                return Zn(int(self) + other)
            return NotImplemented

        def __radd__(self, other):
            """reversed addition (commutative!)"""
            return self + other

        def __sub__(self, other):
            """subtraction"""
            if isinstance(other, Zn):
                return Zn(int(self) - int(other))
            if type(other) == int:
                return Zn(int(self) - other)
            return NotImplemented

        def __rsub__(self, other):
            """reversed subtraction"""
            return - self + other

        def __mul__(self, other):
            """multiplication"""
            if isinstance(other, Zn):
                return Zn(int(self) * int(other))
            if type(other) == int:
                return Zn(int(self) * other)
            return NotImplemented

        def __rmul__(self, other):
            """reversed multiplication (commutative!)"""
            return self * other

        @property
        def inverse(self):
            """return the multiplicative inverse

            EXCEPTIONS

                ZeroDivisionError is raised if the number is 0
                or a zero divisor.
            """
            k = int(self)
            if reciprocal := self.__inverses.get(k):
                return reciprocal
            self.ord            # calculate the order
            return self.__inverses[k]

        @property
        def reciprocal(self):
            """alias for self.inverse"""
            return self.inverse

        def __truediv__(self, other):
            """divide self by other"""
            if isinstance(other, Zn):
                return self * other.inverse
            if isinstance(other, int):
                other = Zn(other)
                return self * other.inverse
            return NotImplemented

        def __rtruediv(self, other):
            """divide other by self (not commutative!)"""
            return self.inverse * other

    Zn.__name__ = ring = f"ℤ/{n}"
    Zn.__doc__ = f"{ring} (integers modulo {n})\n\nDESCRIPTION\n"
    paragraph = ring + " is the commutative ring of integers modulo n="
    paragraph += str(n) + ". Since n is "
    paragraph += "prime" if prime else "composite"
    paragraph += ", it follows that " + ring + " "
    paragraph += "is a field" if prime else "has divisors of zero"
    paragraph += "."
    for line in textwrap.wrap(paragraph, initial_indent='    ',
                              subsequent_indent='    ',
                              fix_sentence_endings=True):
        Zn.__doc__ += "\n" + line
    if not prime:
        Zn.__doc__ += "\n\nNOTE\n"
        paragraph = f"{n=} factors as "
        paragraph += "×".join(_factors(n)) + ". "
        paragraph += f"ℤ/{n} has {len(zd)} divisors of zero (including zero) "
        paragraph += f"and {Zn.multiplicative_order()} units in its "
        paragraph += "multiplicative group. "
        paragraph += "The group of units is "
        if not Zn.is_cyclic():
            paragraph += "not "
        paragraph += "cyclic."
        for line in textwrap.wrap(paragraph, initial_indent='    ',
                                  subsequent_indent='    ',
                                  fix_sentence_endings=True):
            Zn.__doc__ += "\n" + line
    return Zn

# END utilities.modn
